apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: bookinfo
  namespace: default
spec:
  targets:
    - name: productpage
    - name: reviews
    - name: ratings
    - name: details
  peers:
    - mtls:
        mode: STRICT
---
